import type { Metadata } from "next";
import { Red_Hat_Text} from "next/font/google";
import "./globals.css";

const redHatText = Red_Hat_Text({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:["400", "600", "700"],
  
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} antialiased`}
      >
        <main className="min-h-screen max-w-[1440px] mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
